version: '3'
services:

  postgres_db:
    image: postgres:latest
    container_name: postgres_db
    env_file:
      - .env.local
    volumes:
      - postgres_db:/etc/postgresql/data/pgdata
    ports:
      - "5432:5432"
    restart: always

  es:
    image: elasticsearch:latest
    container_name: elasticsearch
    restart: always
    environment:
      - discovery.type=single-node
      - "ES_JAVA_OPTS=-Xms200m -Xmx200m"
      - xpack.security.enabled=false
      - ingest.geoip.downloader.enabled=false
    volumes:
      - elasticsearch_data:/opt/elasticsearch/data
    ports:
      - "9200:9200"
    env_file:
      - ./.env

  etl:
    build: ./postgres_to_es
    container_name: etl
    restart: always
    env_file:
      - .env

  redis: 
    image: redis:latest
    ports:
      - "6379:6379"
    volumes:
      - ./redis_data:/data
    env_file: 
      - .env

volumes:
  postgres_db:
  elasticsearch_data: